sudo: required

language: node_js

addons:
  apt
    - sources: google-chrome
    - packages: google-chrome-stable

before_install:
  - npm i -g npm@6

node_js:
  - "8"
  - "11.10.1"

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
before_script:
  - npm run setup
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3                   # give xvfb some time to start

script:
  - npm run lint:nofix
  - npm run test
  - npm run bench
