sudo: required

language: node_js

before_install:
  - npm i -g npm@6

node_js:
  - "8"
  - "11.10.1"

before_script:
  - npm run setup

script:
  - npm run lint:nofix
  - npm run test

jobs: 
  include:
    - stage: bench
      addons:
        apt:
          sources: google-chrome
          packages: google-chrome-stable
      skip_cleanup: true
      before_script:
        - npm run setup
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3                   # give xvfb some time to start
      script: npm run bench

stages:
  - test # default stage
  - name: bench
    # require the branch name to be master (note for PRs this is the base branch name)
    if: (branch = master AND type != pull_request) OR branch =~ ^bench