sudo: required

language: node_js

before_install:
  - npm i -g npm@6
  - npm i eslint -g

node_js:
  - "8"
  - "12"

before_script:
  - npm run setup

script:
  - npm run lint:nofix
  - npm run test


jobs:
  include:
    - stage: bench
      addons:
        apt:
          sources: google-chrome
          packages: google-chrome-stable
      skip_cleanup: true
      # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb
      services:
        - xvfb
      script: npm run bench

    - stage: auto-publisher
      script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - npm run check-and-publish

stages:
  - test # default stage
  - name: bench
    # require the branch name to be master (note for PRs this is the base branch name)
    if: (branch = master AND type != pull_request) OR branch =~ ^bench
  - name: auto-publisher
    if: (branch = master AND type != pull_request) OR branch =~ ^releases
