sudo: required

os:
  - osx

language: node_js

addons:
  chrome: beta

before_install:
  - npm i -g npm@6

node_js:
  - "8"
  - "11.10.1"

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
before_script:
  - npm run setup
  - export DISPLAY=:99.0
  - sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok
  - sleep 3                             # give xvfb some time to start

script:
  - npm run lint:nofix
  - npm run test
  - npm run bench
